# This is the configuration used to check the rubocop source code.
require:
  - rubocop-performance
  
AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
